adx_accountrelationship: 
adx_append: false
adx_appendto: false
adx_childTablePermissions: []
adx_contactrelationship: 
adx_create: false
adx_delete: false
adx_entitylogicalname: sample_creditcardapplication
adx_entityname: Credit Card Application Table Permissions - Reviewer
adx_entitypermission_webrole:
- 18c1fdce-684b-f011-877a-7c1e520c8613
adx_entitypermissionid: 71ecf203-dfe2-4c1e-9db2-112ed3925a52
adx_filecontent: 
adx_parententitypermission: 
adx_parentrelationship: 
adx_read: true
adx_scope: 756150000
adx_write: true
