append: false
appendto: false
create: false
delete: false
entitylogicalname: sample_creditcardapplication
entityname: Credit Card Application Table Permissions - Reviewer
entitypermission_webrole:
- 18c1fdce-684b-f011-877a-7c1e520c8613
id: 71ecf203-dfe2-4c1e-9db2-112ed3925a52
parententitypermission: 
read: true
scope: 756150000
write: true
