append: false
appendto: false
create: true
delete: false
entitylogicalname: sample_creditcardapplication
entityname: Credit Card Application Table Permission - Authenticated
entitypermission_webrole:
- a4f542e4-9963-433b-9f79-8ec001a99500
id: f18d3981-479f-4179-b8d7-4b1d1658423c
parententitypermission: 
read: true
scope: 756150000
write: false
