name: "GitHub Repo Stats"

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

permissions:
  contents: read

jobs:
  j1:
    name: repostats-for-nice-project
    runs-on: ubuntu-latest
    steps:
      - name: generate app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 2740120
          private-key: ${{ secrets.POWER_PAGES_PUBLIC_GITHUB_APP_PRIVATE_KEY }}

      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@RELEASE
        with:
          repository: microsoft/power-pages-samples
          ghtoken: ${{ steps.app-token.outputs.token }}
          databranch: github-repo-stats
          ghpagesprefix: https://microsoft.github.io/power-pages-samples
